### ISSUE TITLE
Compiling with typescript does not work

### ISSUE THREAD

**Issue by jonaskello** [tentwentyfour/nextcloud-link#3]
I try to use this package but when I compile with `tsc` I get this error:

```
$ tsc -b packages && yarn promaster-markdown-build-esm
node_modules/nextcloud-link/compiled/source/types.d.ts:4:38 - error TS7019: Rest parameter 'parameters' implicitly has an 'any[]' type.
```

This is using latest version 1.0.16. Is there a fix for this?

**Comment by floriansimon1** [comment]
I think this might be due to your tsconfig. Do you maybe use the `noImplicitAny` feature of Typescript?

**Comment by floriansimon1** [comment]
I believe v1.0.17 should address the issue. Let me know if it doesn't

**Comment by jonaskello** [comment]
Yes, confirmed it compiles with v1.0.17 :-). 
Thanks for the quick fix 👍 🚀
